function characterAsset(id, fileName, label, group) {
  return {
    id,
    category: "characters",
    fileName: `characters/${fileName}`,
    label,
    alt: `《洛神》${group}角色资产：${label}`,
  };
}

export const luoshenCharacterAssets = [
  characterAsset("luoshen-main-01", "character-main-01.webp", "韩震", "主要"),
  characterAsset("luoshen-main-02", "character-main-02.webp", "林仙儿", "主要"),
  characterAsset("luoshen-main-03", "character-main-03.webp", "林仙儿白衣持枪", "主要"),
  characterAsset("luoshen-main-04", "character-main-04.webp", "刘牧", "主要"),
  characterAsset("luoshen-main-05", "character-main-05.webp", "刘牧变身后", "主要"),
  characterAsset("luoshen-main-06", "character-main-06.webp", "刘牧穿越后", "主要"),
  characterAsset("luoshen-main-07", "character-main-07.webp", "刘牧穿越前", "主要"),
  characterAsset("luoshen-main-08", "character-main-08.webp", "刘牧战斗后", "主要"),
  characterAsset("luoshen-main-09", "character-main-09.webp", "刘牧镇魔司服饰", "主要"),
  characterAsset("luoshen-main-10", "character-main-10.webp", "洛神 01", "主要"),
  characterAsset("luoshen-main-11", "character-main-11.webp", "洛神 02", "主要"),
  characterAsset("luoshen-main-12", "character-main-12.webp", "主要角色全家福", "主要"),
  characterAsset("luoshen-main-13", "character-main-13.webp", "主要角色概念 01", "主要"),
  characterAsset("luoshen-main-14", "character-main-14.webp", "主要角色概念 02", "主要"),
  characterAsset("luoshen-main-15", "character-main-15.webp", "主要角色概念 03", "主要"),
  characterAsset("luoshen-main-16", "character-main-16.webp", "斩业刀 01", "主要"),
  characterAsset("luoshen-main-17", "character-main-17.webp", "斩业刀 02", "主要"),
  characterAsset("luoshen-main-18", "character-main-18.webp", "主要角色设定 01", "主要"),
  characterAsset("luoshen-main-19", "character-main-19.webp", "主要角色设定 02", "主要"),
  characterAsset("luoshen-main-20", "character-main-20.webp", "主要角色设定 03", "主要"),
  characterAsset("luoshen-main-21", "character-main-21.webp", "主要角色设定 04", "主要"),
  characterAsset("luoshen-main-22", "character-main-22.webp", "主要角色设定 05", "主要"),
  characterAsset("luoshen-main-23", "character-main-23.webp", "主要角色设定 06", "主要"),
  characterAsset("luoshen-main-24", "character-main-24.webp", "主要角色设定 07", "主要"),
  characterAsset("luoshen-main-25", "character-main-25.webp", "主要角色设定 08", "主要"),
  characterAsset("luoshen-main-26", "character-main-26.webp", "主要角色设定 09", "主要"),
  characterAsset("luoshen-main-27", "character-main-27.webp", "主要角色设定 10", "主要"),
  characterAsset("luoshen-main-28", "character-main-28.webp", "主要角色设定 11", "主要"),
  characterAsset("luoshen-main-29", "character-main-29.webp", "Q 版刘牧", "主要"),
  characterAsset("luoshen-support-01", "character-support-01.webp", "二号杂兵", "配角"),
  characterAsset("luoshen-support-02", "character-support-02.webp", "老村长", "配角"),
  characterAsset("luoshen-support-03", "character-support-03.webp", "六号杂兵", "配角"),
  characterAsset("luoshen-support-04", "character-support-04.webp", "三号杂兵", "配角"),
  characterAsset("luoshen-support-05", "character-support-05.webp", "四号杂兵", "配角"),
  characterAsset("luoshen-support-06", "character-support-06.webp", "王崇文", "配角"),
  characterAsset("luoshen-support-07", "character-support-07.webp", "王崇文全景图", "配角"),
  characterAsset("luoshen-support-08", "character-support-08.webp", "王崇武", "配角"),
  characterAsset("luoshen-support-09", "character-support-09.webp", "王崇武全景图", "配角"),
  characterAsset("luoshen-support-10", "character-support-10.webp", "王管家", "配角"),
  characterAsset("luoshen-support-11", "character-support-11.webp", "王管家全景图", "配角"),
  characterAsset("luoshen-support-12", "character-support-12.webp", "五号杂兵", "配角"),
  characterAsset("luoshen-support-13", "character-support-13.webp", "小草", "配角"),
  characterAsset("luoshen-support-14", "character-support-14.webp", "小草全景图", "配角"),
  characterAsset("luoshen-support-15", "character-support-15.webp", "一号杂兵", "配角"),
  characterAsset("luoshen-support-16", "character-support-16.webp", "赵大伯", "配角"),
  characterAsset("luoshen-support-17", "character-support-17.webp", "赵大伯全景图", "配角"),
  characterAsset("luoshen-support-18", "character-support-18.webp", "赵大娘", "配角"),
  characterAsset("luoshen-support-19", "character-support-19.webp", "赵大娘全景图", "配角"),
  characterAsset("luoshen-support-20", "character-support-20.webp", "配角设定 01", "配角"),
  characterAsset("luoshen-support-21", "character-support-21.webp", "配角设定 02", "配角"),
  characterAsset("luoshen-support-22", "character-support-22.webp", "配角设定 03", "配角"),
];
