export const bundledProjects = [
  {
    id: "short-drama-heidalao",
    category: "shortDrama",
    title: "黑老大",
    type: "短剧",
    description: "短剧作品《黑老大》",
    coverFileName: "projects/heidalao-cover.webp",
    videoFileName: "videos/heidalao.mp4",
  },
  {
    id: "short-drama-gaocuolianyin",
    category: "shortDrama",
    title: "搞错联姻对象",
    type: "短剧",
    description: "短剧作品《搞错联姻对象》",
    coverFileName: "projects/gaocuolianyin-cover.webp",
    videoFileName: "videos/gaocuolianyin.mp4",
  },
  {
    id: "short-drama-biaoge",
    category: "shortDrama",
    title: "表哥",
    type: "短剧",
    description: "短剧作品《表哥》",
    coverFileName: "projects/biaoge-cover.webp",
    videoFileName: "videos/biaoge.mp4",
  },
  {
    id: "short-drama-dandao",
    category: "shortDrama",
    title: "丹道",
    type: "短剧",
    description: "短剧作品《丹道》",
    coverFileName: "projects/dandao-cover.webp",
    videoFileName: "videos/dandao.mp4",
  },
  {
    id: "short-drama-ludishenxian",
    category: "shortDrama",
    title: "陆地神仙",
    type: "短剧",
    description: "短剧作品《陆地神仙》",
    coverFileName: "projects/ludishenxian-cover.webp",
    videoFileName: "videos/ludishenxian.mp4",
  },
  {
    id: "short-drama-jiehunfusi",
    category: "shortDrama",
    title: "他要结婚我要赴死",
    type: "短剧",
    description: "短剧作品《他要结婚我要赴死》",
    coverFileName: "projects/jiehunfusi-cover.webp",
    videoFileName: "videos/jiehunfusi.mp4",
  },
];
