export const bundledProjects = [
  {
    id: "short-drama-heidalao",
    category: "shortDrama",
    title: "黑老大",
    type: "短剧",
    description: "短剧作品《黑老大》",
    coverFileName: "projects/heidalao-cover.webp",
    videoFileName: "videos/heidalao.mp4",
  },
  {
    id: "short-drama-gaocuolianyin",
    category: "shortDrama",
    title: "搞错联姻对象",
    type: "短剧",
    description: "短剧作品《搞错联姻对象》",
    coverFileName: "projects/gaocuolianyin-cover.webp",
    videoFileName: "videos/gaocuolianyin.mp4",
  },
  {
    id: "short-drama-biaoge",
    category: "shortDrama",
    title: "表哥",
    type: "短剧",
    description: "短剧作品《表哥》",
    coverFileName: "projects/biaoge-cover.webp",
    videoFileName: "videos/biaoge.mp4",
  },
  {
    id: "short-drama-dandao",
    category: "shortDrama",
    title: "丹道",
    type: "短剧",
    description: "短剧作品《丹道》",
    coverFileName: "projects/dandao-cover.webp",
    videoFileName: "videos/dandao.mp4",
  },
  {
    id: "short-drama-ludishenxian",
    category: "shortDrama",
    title: "陆地神仙",
    type: "短剧",
    description: "短剧作品《陆地神仙》",
    coverFileName: "projects/ludishenxian-cover.webp",
    videoFileName: "videos/ludishenxian.mp4",
  },
  {
    id: "short-drama-jiehunfusi",
    category: "shortDrama",
    title: "他要结婚我要赴死",
    type: "短剧",
    description: "短剧作品《他要结婚我要赴死》",
    coverFileName: "projects/jiehunfusi-cover.webp",
    videoFileName: "videos/jiehunfusi.mp4",
  },
  {
    id: "short-drama-mangxin",
    category: "shortDrama",
    title: "盲信",
    type: "短剧",
    description: "短剧作品《盲信》",
    coverFileName: "projects/mangxin-cover.webp",
    videoFileName: "videos/mangxin.mp4",
  },
  {
    id: "short-drama-xiaohunv",
    category: "shortDrama",
    title: "小狐女",
    type: "短剧",
    description: "短剧作品《小狐女》",
    coverFileName: "projects/xiaohunv-cover.webp",
    videoFileName: "videos/xiaohunv.mp4",
  },
  {
    id: "mozun-fanpai-episode-1",
    category: "mozunFanpai",
    title: "第一集",
    type: "系列短剧 · 第 1 集",
    description: "《被魔尊附体后我成反派了》第一集",
    coverFileName: "projects/mozun-ep1-cover.webp",
    videoFileName: "videos/mozun-ep1.mp4",
  },
  {
    id: "mozun-fanpai-episode-2",
    category: "mozunFanpai",
    title: "第二集",
    type: "系列短剧 · 第 2 集",
    description: "《被魔尊附体后我成反派了》第二集",
    coverFileName: "projects/mozun-ep2-cover.webp",
    videoFileName: "videos/mozun-ep2.mp4",
  },
  {
    id: "mozun-fanpai-episode-3",
    category: "mozunFanpai",
    title: "第三集",
    type: "系列短剧 · 第 3 集",
    description: "《被魔尊附体后我成反派了》第三集",
    coverFileName: "projects/mozun-ep3-cover.webp",
    videoFileName: "videos/mozun-ep3.mp4",
  },
  {
    id: "mozun-fanpai-episode-4",
    category: "mozunFanpai",
    title: "第四集",
    type: "系列短剧 · 第 4 集",
    description: "《被魔尊附体后我成反派了》第四集",
    coverFileName: "projects/mozun-ep4-cover.webp",
    videoFileName: "videos/mozun-ep4.mp4",
  },
  {
    id: "mozun-fanpai-episode-5",
    category: "mozunFanpai",
    title: "第五集",
    type: "系列短剧 · 第 5 集",
    description: "《被魔尊附体后我成反派了》第五集",
    coverFileName: "projects/mozun-ep5-cover.webp",
    videoFileName: "videos/mozun-ep5.mp4",
  },
  {
    id: "mozun-fanpai-episode-6",
    category: "mozunFanpai",
    title: "第六集",
    type: "系列短剧 · 第 6 集",
    description: "《被魔尊附体后我成反派了》第六集",
    coverFileName: "projects/mozun-ep6-cover.webp",
    videoFileName: "videos/mozun-ep6.mp4",
  },
  {
    id: "mozun-fanpai-episode-7",
    category: "mozunFanpai",
    title: "第七集",
    type: "系列短剧 · 第 7 集",
    description: "《被魔尊附体后我成反派了》第七集",
    coverFileName: "projects/mozun-ep7-cover.webp",
    videoFileName: "videos/mozun-ep7.mp4",
  },
  {
    id: "mozun-fanpai-episode-8",
    category: "mozunFanpai",
    title: "第八集",
    type: "系列短剧 · 第 8 集",
    description: "《被魔尊附体后我成反派了》第八集",
    coverFileName: "projects/mozun-ep8-cover.webp",
    videoFileName: "videos/mozun-ep8.mp4",
  },
  {
    id: "mozun-fanpai-episode-9",
    category: "mozunFanpai",
    title: "第九集",
    type: "系列短剧 · 第 9 集",
    description: "《被魔尊附体后我成反派了》第九集",
    coverFileName: "projects/mozun-ep9-cover.webp",
    videoFileName: "videos/mozun-ep9.mp4",
  },
  {
    id: "mozun-fanpai-episode-10",
    category: "mozunFanpai",
    title: "第十集",
    type: "系列短剧 · 第 10 集",
    description: "《被魔尊附体后我成反派了》第十集",
    coverFileName: "projects/mozun-ep10-cover.webp",
    videoFileName: "videos/mozun-ep10.mp4",
  },
  {
    id: "other-dance",
    category: "otherWorks",
    title: "舞蹈",
    type: "视觉短片",
    description: "舞蹈视觉作品",
    coverFileName: "projects/other-dance-cover.webp",
    videoFileName: "videos/other-dance.mp4",
  },
  {
    id: "other-conflict",
    category: "otherWorks",
    title: "矛盾",
    type: "冲突短片",
    description: "戏剧冲突视觉作品《矛盾》",
    coverFileName: "projects/other-conflict-cover.webp",
    videoFileName: "videos/other-conflict.mp4",
  },
  {
    id: "other-fight",
    category: "otherWorks",
    title: "打斗成片",
    type: "动作短片",
    description: "动作打斗视觉作品",
    coverFileName: "projects/other-fight-cover.webp",
    videoFileName: "videos/other-fight.mp4",
  },
  {
    id: "other-ink-wuxia",
    category: "otherWorks",
    title: "水墨武侠",
    type: "水墨短片",
    description: "水墨风格武侠视觉作品",
    coverFileName: "projects/other-ink-wuxia-cover.webp",
    videoFileName: "videos/other-ink-wuxia.mp4",
  },
  {
    id: "other-xiyou-system",
    category: "otherWorks",
    title: "西游系统",
    type: "AI 漫剧",
    description: "西游题材 AI 漫剧作品",
    coverFileName: "projects/other-xiyou-system-cover.webp",
    videoFileName: "videos/other-xiyou-system.mp4",
  },
  {
    id: "other-live-fight",
    category: "otherWorks",
    title: "真人打斗",
    type: "动作短片",
    description: "真人动作打斗作品",
    coverFileName: "projects/other-live-fight-cover.webp",
    videoFileName: "videos/other-live-fight.mp4",
  },
  {
    id: "other-epic-wuxia",
    category: "otherWorks",
    title: "震撼武侠",
    type: "武侠短片",
    description: "震撼武侠视觉作品",
    coverFileName: "projects/other-epic-wuxia-cover.webp",
    videoFileName: "videos/other-epic-wuxia.mp4",
  },
];
